export interface ScaffoldInput {
	bucketTemplate: string;
	keyTemplate: string;
	stacks: string[];
	envs: string[];
	regions: string[];
	project: string;
	appName?: string;
	role?: string;
}

export function scaffoldSubspaceToml(input: ScaffoldInput): string {
	const lines: string[] = [];

	lines.push(`# Generated by \`subspace migrate init\`.`);
	lines.push(`# discovered stacks: ${input.stacks.join(", ")}`);
	lines.push(`# discovered envs: ${input.envs.join(", ")}`);
	lines.push("");

	lines.push(`[project]`);
	lines.push(`backend = "s3"`);
	lines.push("");

	lines.push(`[migration]`);
	lines.push(`source = "terraspace"`);
	lines.push("");

	lines.push(`[migration.terraspace]`);
	lines.push(`bucket_template = "${input.bucketTemplate}"`);
	lines.push(`key_template = "${input.keyTemplate}"`);
	lines.push(`project = "${input.project}"`);
	lines.push(`regions = [${input.regions.map((r) => `"${r}"`).join(", ")}]`);
	if (input.envs.length) {
		lines.push(
			`envs = [${input.envs.map((e) => `"${e}"`).join(", ")}]`,
		);
	}
	if (input.appName) {
		lines.push(`app_name = "${input.appName}"`);
	}
	if (input.role) {
		lines.push(`role = "${input.role}"`);
	}
	lines.push("");

	return lines.join("\n");
}
