import type { SubspaceContext } from "../context.js";

type GeneratorKind = "project" | "module" | "stack";
type ProjectBackend = "local" | "s3" | "gcs" | "azurerm";

const VALID_NAME = /^[A-Za-z0-9_-]+$/;
const VALID_BACKENDS = new Set<ProjectBackend>([
	"local",
	"s3",
	"gcs",
	"azurerm",
]);

export async function runNew(
	ctx: SubspaceContext,
	input: {
		generator: GeneratorKind;
		name: string;
		backend?: ProjectBackend;
		region?: string;
	},
): Promise<number> {
	if (!VALID_NAME.test(input.name)) {
		ctx.log.error(
			`invalid name "${input.name}". Use letters, numbers, hyphens, or underscores.`,
		);
		return 1;
	}
	if (input.generator === "project" && input.backend && !VALID_BACKENDS.has(input.backend)) {
		ctx.log.error(
			`invalid backend "${input.backend}". Use local, s3, gcs, or azurerm.`,
		);
		return 1;
	}

	switch (input.generator) {
		case "project":
			return generateProject(
				ctx,
				input.name,
				input.backend ?? "local",
				resolveRegion(input.backend ?? "local", input.region),
			);
		case "module":
			return generateModule(ctx, input.name);
		case "stack":
			return generateStack(ctx, input.name);
	}
}

async function generateProject(
	ctx: SubspaceContext,
	name: string,
	backend: ProjectBackend,
	region: string | undefined,
): Promise<number> {
	if (await ctx.fs.exists(name)) {
		ctx.log.error(`project "${name}" already exists`);
		return 1;
	}

	await ctx.fs.mkdir(`${name}/app/modules`, { recursive: true });
	await ctx.fs.mkdir(`${name}/app/stacks`, { recursive: true });
	await ctx.fs.mkdir(`${name}/config/terraform`, { recursive: true });

	await writeFiles(ctx, {
		[`${name}/README.md`]: `# ${name}

Generated by Subspace.
`,
		[`${name}/.gitignore`]: `.subspace/
**/*.local.tfvars
**/*.secrets.tfvars
`,
		[`${name}/app/modules/.keep`]: "",
		[`${name}/app/stacks/.keep`]: "",
		[`${name}/config/terraform/backend.tf`]: projectBackendTemplate(backend, region),
	});

	ctx.log.info(`Created project: ${name} (backend: ${backend})`);
	return 0;
}

async function generateModule(
	ctx: SubspaceContext,
	name: string,
): Promise<number> {
	if (!(await ctx.fs.exists("app/modules"))) {
		ctx.log.error('app/modules/ not found. Run this inside a Subspace project.');
		return 1;
	}

	const moduleDir = `app/modules/${name}`;
	if (await ctx.fs.exists(moduleDir)) {
		ctx.log.error(`module "${name}" already exists`);
		return 1;
	}

	await ctx.fs.mkdir(moduleDir, { recursive: true });
	await writeFiles(ctx, {
		[`${moduleDir}/main.tf`]: `# Module resources
`,
		[`${moduleDir}/variables.tf`]: `# Module inputs
`,
		[`${moduleDir}/outputs.tf`]: `# Module outputs
`,
	});

	ctx.log.info(`Created module: ${moduleDir}`);
	return 0;
}

async function generateStack(
	ctx: SubspaceContext,
	name: string,
): Promise<number> {
	if (!(await ctx.fs.exists("app/stacks"))) {
		ctx.log.error('app/stacks/ not found. Run this inside a Subspace project.');
		return 1;
	}

	const stackDir = `app/stacks/${name}`;
	if (await ctx.fs.exists(stackDir)) {
		ctx.log.error(`stack "${name}" already exists`);
		return 1;
	}

	const backendConfig = await readProjectBackendConfig(ctx);

	await ctx.fs.mkdir(`${stackDir}/tfvars`, { recursive: true });
	await writeFiles(ctx, {
		[`${stackDir}/main.tf`]: `# Stack resources
`,
		[`${stackDir}/backend.tf`]: `terraform {
  backend "local" {}
}
`,
		[`${stackDir}/providers.tf`]: stackProviderTemplate(
			backendConfig.backend,
			backendConfig.region,
		),
		[`${stackDir}/tfvars/base.tfvars`]: `# Base vars
`,
	});

	ctx.log.info(`Created stack: ${stackDir}`);
	return 0;
}

async function writeFiles(
	ctx: SubspaceContext,
	files: Record<string, string>,
): Promise<void> {
	for (const [path, content] of Object.entries(files)) {
		await ctx.fs.writeFile(path, content);
	}
}

function projectBackendTemplate(
	backend: ProjectBackend,
	region: string | undefined,
): string {
	switch (backend) {
		case "local":
			return `terraform {
  backend "local" {}
}
`;
		case "s3":
			return `terraform {
  backend "s3" {
    bucket = "replace-me-tfstate"
    region = "${region ?? "us-east-1"}"
  }
}
`;
		case "gcs":
			return `terraform {
  backend "gcs" {
    bucket = "replace-me-tfstate"
  }
}
`;
		case "azurerm":
			return `terraform {
  backend "azurerm" {
    resource_group_name  = "replace-me-rg"
    storage_account_name = "replacemetfstate"
    container_name       = "tfstate"
  }
}
`;
	}
}

function stackProviderTemplate(
	backend: ProjectBackend,
	region: string | undefined,
): string {
	switch (backend) {
		case "local":
			return `terraform {
  required_version = ">= 1.6.0"
}
`;
		case "s3":
			return `terraform {
  required_version = ">= 1.6.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "${region ?? "us-east-1"}"
}
`;
		case "gcs":
			return `terraform {
  required_version = ">= 1.6.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }
}

provider "google" {
  project = "replace-me-project-id"
  region  = "${region ?? "us-central1"}"
}
`;
		case "azurerm":
			return `terraform {
  required_version = ">= 1.6.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

provider "azurerm" {
  features {}
}
`;
	}
}

function resolveRegion(
	backend: ProjectBackend,
	region: string | undefined,
): string | undefined {
	if (backend === "s3") return region ?? "us-east-1";
	if (backend === "gcs") return region ?? "us-central1";
	return undefined;
}

async function readProjectBackendConfig(
	ctx: SubspaceContext,
): Promise<{ backend: ProjectBackend; region: string | undefined }> {
	const path = "config/terraform/backend.tf";
	if (!(await ctx.fs.exists(path))) {
		return { backend: "local", region: undefined };
	}

	let content = "";
	try {
		content = await ctx.fs.readFile(path);
	} catch {
		return { backend: "local", region: undefined };
	}

	const backendMatch = content.match(/backend\s+"(local|s3|gcs|azurerm)"/);
	const backend = (backendMatch?.[1] as ProjectBackend | undefined) ?? "local";
	const regionMatch = content.match(/region\s*=\s*"([A-Za-z0-9-]+)"/);
	const region = regionMatch?.[1];
	return { backend, region: resolveRegion(backend, region) };
}
