import {
	loadProjectConfig,
	serializeProjectConfig,
} from "../config/project.js";
import { saveStackConfig } from "../config/stack.js";
import type { SubspaceContext } from "../context.js";
import {
	type BackendType,
	defaultBackendSettings,
	renderBackendTf,
} from "../domain/backends.js";
import {
	defaultProviderSettings,
	type ProviderType,
	recommendedBackendForProvider,
	recommendedProviderForBackend,
	renderProviderTf,
} from "../domain/providers.js";

type GeneratorKind = "project" | "module" | "stack";

const VALID_NAME = /^[A-Za-z0-9_-]+$/;
const VALID_BACKENDS = new Set<BackendType>(["local", "s3", "gcs", "azurerm"]);
const VALID_PROVIDERS = new Set<ProviderType>([
	"aws",
	"azure",
	"gcp",
	"cloudflare",
]);

interface NewInput {
	generator: GeneratorKind;
	name: string;
	backend?: string;
	provider?: string;
	region?: string;
}

export async function runNew(
	ctx: SubspaceContext,
	input: NewInput,
): Promise<number> {
	if (!VALID_NAME.test(input.name)) {
		ctx.log.error(
			`invalid name "${input.name}". Use letters, numbers, hyphens, or underscores.`,
		);
		return 1;
	}
	if (input.backend && !VALID_BACKENDS.has(input.backend as BackendType)) {
		ctx.log.error(
			`invalid backend "${input.backend}". Use local, s3, gcs, or azurerm.`,
		);
		return 1;
	}
	if (input.provider && !VALID_PROVIDERS.has(input.provider as ProviderType)) {
		ctx.log.error(
			`invalid provider "${input.provider}". Use aws, azure, gcp, or cloudflare.`,
		);
		return 1;
	}

	const backend = input.backend as BackendType | undefined;
	const provider = input.provider as ProviderType | undefined;

	switch (input.generator) {
		case "project":
			return generateProject(
				ctx,
				input.name,
				backend ?? "local",
				input.region,
				provider,
			);
		case "module":
			return generateModule(ctx, input.name);
		case "stack":
			return generateStack(ctx, input.name, provider, input.region);
	}
}

async function generateProject(
	ctx: SubspaceContext,
	name: string,
	backend: BackendType,
	region: string | undefined,
	provider?: ProviderType,
): Promise<number> {
	if (await ctx.fs.exists(name)) {
		ctx.log.error(`project "${name}" already exists`);
		return 1;
	}

	const settings = defaultBackendSettings(backend, { region });

	await ctx.fs.mkdir(`${name}/app/modules`, { recursive: true });
	await ctx.fs.mkdir(`${name}/app/stacks`, { recursive: true });
	await ctx.fs.mkdir(`${name}/config/terraform`, { recursive: true });

	await writeFiles(ctx, {
		[`${name}/README.md`]: `# ${name}

Generated by Subspace.
`,
		[`${name}/.gitignore`]: `.subspace/
**/*.local.tfvars
**/*.secrets.tfvars
`,
		[`${name}/app/modules/.keep`]: "",
		[`${name}/app/stacks/.keep`]: "",
		[`${name}/config/terraform/backend.tf`]: renderBackendTf(backend, settings),
	});

	await ctx.fs.writeFile(
		`${name}/subspace.toml`,
		serializeProjectConfig({
			project: { backend, provider },
			backend: settings,
		}),
	);

	ctx.log.info(
		`Created project: ${name} (backend: ${backend}${provider ? `, provider: ${provider}` : ""})`,
	);
	return 0;
}

async function generateModule(
	ctx: SubspaceContext,
	name: string,
): Promise<number> {
	if (!(await ctx.fs.exists("app/modules"))) {
		ctx.log.error(
			"app/modules/ not found. Run this inside a Subspace project.",
		);
		return 1;
	}

	const moduleDir = `app/modules/${name}`;
	if (await ctx.fs.exists(moduleDir)) {
		ctx.log.error(`module "${name}" already exists`);
		return 1;
	}

	await ctx.fs.mkdir(moduleDir, { recursive: true });
	await writeFiles(ctx, {
		[`${moduleDir}/main.tf`]: `# Module resources
`,
		[`${moduleDir}/variables.tf`]: `# Module inputs
`,
		[`${moduleDir}/outputs.tf`]: `# Module outputs
`,
	});

	ctx.log.info(`Created module: ${moduleDir}`);
	return 0;
}

async function generateStack(
	ctx: SubspaceContext,
	name: string,
	providerOverride: ProviderType | undefined,
	regionOverride: string | undefined,
): Promise<number> {
	if (!(await ctx.fs.exists("app/stacks"))) {
		ctx.log.error("app/stacks/ not found. Run this inside a Subspace project.");
		return 1;
	}

	const stackDir = `app/stacks/${name}`;
	if (await ctx.fs.exists(stackDir)) {
		ctx.log.error(`stack "${name}" already exists`);
		return 1;
	}

	const loadedConfig = await loadProjectConfig(ctx);
	const projectConfig =
		loadedConfig ??
		(await inferProjectConfigFromLegacyFiles(ctx).then((inferred) => ({
			project: {
				backend: inferred.backend,
				provider: undefined as ProviderType | undefined,
			},
			backend: { region: inferred.region },
		})));
	const backend = projectConfig!.project.backend;
	const provider =
		providerOverride ??
		projectConfig!.project.provider ??
		recommendedProviderForBackend(backend);
	const providerSettings = defaultProviderSettings(provider, {
		region: regionOverride ?? projectConfig!.backend.region,
	});
	const recommendedBackend = recommendedBackendForProvider(provider);
	if (recommendedBackend !== backend) {
		ctx.log.warn(
			`provider "${provider}" recommends backend "${recommendedBackend}" but project backend is "${backend}"`,
		);
	}

	await ctx.fs.mkdir(`${stackDir}/tfvars`, { recursive: true });
	await writeFiles(ctx, {
		[`${stackDir}/main.tf`]: `# Stack resources
`,
		[`${stackDir}/backend.tf`]: renderBackendTf(
			backend,
			projectConfig!.backend,
		),
		[`${stackDir}/providers.tf`]: renderProviderTf(provider, providerSettings),
		[`${stackDir}/tfvars/base.tfvars`]: `# Base vars
`,
	});

	await saveStackConfig(ctx, name, {
		stack: { name, provider },
		regions: {
			values: providerSettings.region ? [providerSettings.region] : [],
			default: providerSettings.region,
		},
		provider: {
			settings: providerSettings,
		},
	});

	ctx.log.info(`Created stack: ${stackDir} (provider: ${provider})`);
	return 0;
}

async function writeFiles(
	ctx: SubspaceContext,
	files: Record<string, string>,
): Promise<void> {
	for (const [path, content] of Object.entries(files)) {
		await ctx.fs.writeFile(path, content);
	}
}

export async function inferProjectConfigFromLegacyFiles(
	ctx: SubspaceContext,
): Promise<{ backend: BackendType; region?: string }> {
	const backendTf = "config/terraform/backend.tf";
	if (!(await ctx.fs.exists(backendTf))) {
		return { backend: "local" };
	}
	const content = await ctx.fs.readFile(backendTf);
	const backend = (content.match(/backend\s+"(local|s3|gcs|azurerm)"/)?.[1] ??
		"local") as BackendType;
	const region = content.match(/region\s*=\s*"([A-Za-z0-9-]+)"/)?.[1];
	return { backend, region };
}
