import { describe, expect, it } from "vitest";
import { extractTemplates } from "../../../src/migrate/terraspace/backend-tf.js";

describe("extractTemplates()", () => {
	it("extracts bucket, key, and region templates from the user's real backend.tf", () => {
		const content = `# This file was initially generated by terraspace_plugin_aws 0.5.0
terraform {
  backend "s3" {
    bucket         = "<%= expansion('terraform-state-:ACCOUNT-:REGION-:ENV') %>"
    key            = "<%= expansion(':PROJECT/:REGION/:APP/:ROLE/:ENV/:EXTRA/:BUILD_DIR/terraform.tfstate') %>"
    region         = "<%= expansion(':REGION') %>"
    encrypt        = true
    dynamodb_table = "terraform_locks"
  }
}`;

		const result = extractTemplates(content);

		expect(result.bucket).toBe("terraform-state-:ACCOUNT-:REGION-:ENV");
		expect(result.key).toBe(
			":PROJECT/:REGION/:APP/:ROLE/:ENV/:EXTRA/:BUILD_DIR/terraform.tfstate",
		);
		expect(result.region).toBe(":REGION");
	});

	it("returns null for fields that are not present", () => {
		const content = `terraform {
  backend "s3" {
    bucket = "<%= expansion('my-bucket') %>"
  }
}`;

		const result = extractTemplates(content);

		expect(result.bucket).toBe("my-bucket");
		expect(result.key).toBeNull();
		expect(result.region).toBeNull();
	});

	it("accepts double-quoted ERB string arguments", () => {
		const content = `bucket = "<%= expansion(\"my-bucket-:ENV\") %>"`;

		const result = extractTemplates(content);

		expect(result.bucket).toBe("my-bucket-:ENV");
	});

	it("tolerates extra whitespace around the expansion call", () => {
		const content = `bucket="<%=  expansion(  'my-bucket'  )  %>"`;

		const result = extractTemplates(content);

		expect(result.bucket).toBe("my-bucket");
	});

	it("returns all-null for completely empty input", () => {
		const result = extractTemplates("");
		expect(result.bucket).toBeNull();
		expect(result.key).toBeNull();
		expect(result.region).toBeNull();
	});

	it("returns null for malformed expansion syntax (missing closing tag)", () => {
		const content = `bucket = "<%= expansion('unterminated`;
		const result = extractTemplates(content);
		expect(result.bucket).toBeNull();
	});

	it("does not match a literal string assignment without ERB wrapping", () => {
		// A user might hardcode `bucket = "my-bucket"` instead of using
		// expansion(). Our extractor only handles the ERB form; the migrate
		// command will need to prompt the user in this case.
		const content = `bucket = "my-bucket"`;
		const result = extractTemplates(content);
		expect(result.bucket).toBeNull();
	});
});
